language: rust
sudo: required
dist: bionic

rust:
  - nightly
  - beta
  - stable
cache: cargo
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

before_script:
  - rustup component add rustfmt
  - rustup component add clippy

script:
  - cargo fmt -- --check
  - cargo clippy
  - cargo build
  - cargo test --verbose

